### ISSUE TITLE
Fix prediction routine of Pareto/NBD for customers with high number of transactions

### ISSUE THREAD

**Issue by mmeierer** [bachmannpatrick/CLVTools#100]
Currently, the prediction routine might produce NaNs for customers with a very high number of transactions. 

Apply the fix which has already been implemented for the standard Pareto/NBD model.

**Comment by bachmannpatrick** [comment]
The issue is caused by PAlive producing NaNs. This can be fixed by rewriting it

**Comment by pschil** [comment]
Is there any minimal example data for which it currently fails or is there an example cbs entry (ie x/t.x/Tcal combination) in order to write tests?

**Comment by bachmannpatrick** [comment]
Some examples that produce NaNs:
x, t.x, T.cal
221, 103.42857, 103.57143
254, 97.42857, 97.28571
161, 94.71429, 98.00000
204, 98.57143, 99.42857
