### ISSUE TITLE
Can't use package with docker image

### ISSUE THREAD

**Issue by dmoimpact** [bachmannpatrick/CLVTools#138]
Hi
I am trying to install the packages using the Rocker / Tidyverse docker image (v 4.0.2).

However, once i try to load the package

I get the following error:

Error: package or namespace load failed for ‘CLVTools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/CLVTools/libs/CLVTools.so':
  libgsl.so.23: cannot open shared object file: No such file or directory

I am not completly sure how to adress this issue. Could it be a  windows / Linux thing?

**Comment by mmeierer** [comment]
CLVTools relies on the GSL library which is an external dependency not an R package.

The GSL library does not come with the docker image "rocker/tidyverse"

To install the library in your docker image follow these steps:

```
docker ps # find the ID of the running container you want to add a package to
docker exec -it <container-id> bash # a docker command to start a bash shell in your container
apt-get update
apt-get install libgsl0-dev # install the package, in this case GSL
```

For more information see here (section "Installing Dependencies external to the R system"):
https://ropenscilabs.github.io/r-docker-tutorial/03-install-packages.html

We will consider adding this information to our documentation.

**Comment by pschil** [comment]
We should also add instructions on how to install from source on Windows with the new package manager in Rtools4.0 (mingw's `pacman`)

**Comment by dmoimpact** [comment]
Thanks so much for the reply. I will try it out and see if I can get it to work!
Documentation for docker would definitely be helpful as I see more and more work being set in production through R running docker instances.

Med venlig hilsen / Best Regards
DANNY MAWANI HOLMGAARD
Lead Analyst
DMO@impactextend.dk
<mailto:DMO@impactextend.dk>
M
T
+45 3120 5092
+45 7020 1619
[cid:image001.png@01D66A62.94B29880]<http://www.impactextend.dk/>
EXTEND YOUR INSIGHTS | EXTEND YOUR IMPACT
AARHUS: Søren Frichs Vej 44D - DK-8230 Åbyhøj
KBH: Laplandsgade 4A, 2. sal - DK-2300 København S

**Comment by mmeierer** [comment]
> We should also add instructions on how to install from source on Windows with the new package manager in Rtools4.0 (mingw's `pacman`)

Agreed. As we did already try out all these ways to compile and install the package, it would be good to document it properly.

**Comment by dmoimpact** [comment]
I agree. This is some incredible work you guys have done !

Med venlig hilsen / Best Regards
DANNY MAWANI HOLMGAARD
Lead Analyst
DMO@impactextend.dk
<mailto:DMO@impactextend.dk>
M
T
+45 3120 5092
+45 7020 1619
[cid:image001.png@01D66A65.5E8E6600]<http://www.impactextend.dk/>
EXTEND YOUR INSIGHTS | EXTEND YOUR IMPACT
AARHUS: Søren Frichs Vej 44D - DK-8230 Åbyhøj
KBH: Laplandsgade 4A, 2. sal - DK-2300 København S

**Comment by dmoimpact** [comment]
Just rebuilt my docker image. Still get the error:

Error: package or namespace load failed for ‘CLVTools’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/usr/local/lib/R/site-library/CLVTools/libs/CLVTools.so':
  libgsl.so.23: cannot open shared object file: No such file or directory

below is my dockerfile:


FROM rocker/tidyverse:4.0.2
MAINTAINER @dannymawani
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
  apt-transport-https \
  curl \
  gnupg \
  unixodbc \
  libmagick++-dev \
  libgsl0-dev \
  && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
  && apt-get update \
  && ACCEPT_EULA=Y apt-get install --yes --no-install-recommends msodbcsql17 \
  && install2.r odbc \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /tmp/*
RUN install2.r --error \
    -r 'http://cran.rstudio.com' \
    gsl CLVTools RODBC doFuture ABCanalysis rjson urltools curl DBI futile.logger furrr future future.apply \
    ## install Github packages
    && Rscript -e "devtools::install_github(c('stenevang/sftp'))" \
    ## clean up
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

Any ideas of what’s missing?

Med venlig hilsen / Best Regards
DANNY MAWANI HOLMGAARD
Lead Analyst
DMO@impactextend.dk
<mailto:DMO@impactextend.dk>
M
T
+45 3120 5092
+45 7020 1619
[cid:image001.png@01D66A66.64786AB0]<http://www.impactextend.dk/>
EXTEND YOUR INSIGHTS | EXTEND YOUR IMPACT
AARHUS: Søren Frichs Vej 44D - DK-8230 Åbyhøj
KBH: Laplandsgade 4A, 2. sal - DK-2300 København S

**Comment by pschil** [comment]
How are you trying to install the CLVTools package itself? 
- from source (source package and `R CMD install`)
- from cran (using `install.packages()`)
- as `apt get r-cran-clvtools`
- from the rstudio linux package manager (rpsm, `install.packages(, repo = "https://demo.rstudiopm.com/cran/__linux__ [......]")`)

**Comment by mmeierer** [comment]
Docker image - as specified above - works for me.

**Comment by dmoimpact** [comment]
The changes worked. Thank you a lot for the help! The reason it did not work before is that docker was not completely updated.

Med venlig hilsen / Best regards

Danny Mawani Holmgaard
Impact Extend
Phone:31205092
w:impactextend.dk  e: dmo@impactextend.dk



Den 4. aug. 2020 kl. 15.03 skrev Markus Meierer <notifications@github.com>:

﻿

Docker image - as specified above - works for me.
