### ISSUE TITLE
Kudos to contributors to this package

### ISSUE THREAD

**Issue by hermandr** [bachmannpatrick/CLVTools#144]
Hi,

I am just writing to congratulate and encourage you for the work you guys have done.
This package is easy to use and apply.
I believe this will increase the adoption of calculating individual CLV.

Thank you again!!!
Great job!

Herman Tan

**Comment by mmeierer** [comment]
Thanks again, @hermandr. As you have considerable experience on applying these kinds of models, you might want to give us your feedback on this idea/proposed feature to increase the adoption of calculating indvidual CLV: https://github.com/bachmannpatrick/CLVTools/issues/147
