### ISSUE TITLE
Comparison of Accuracy of Algorithms

### ISSUE THREAD

**Issue by hermandr** [bachmannpatrick/CLVTools#145]
Hi,

I took one cohort data and ran 3 algorithms with holdout data.
PAlive give probability of alive, actual.x is the trx count.
In order to get accuracy, I run the predicted PAlive against a series of threshold 0.00 to 1.00 and classify the predicted_alive to be 1 or 0.  
The actual trx count, I classify as alive if count > 0.
Then I plot the proportion of the dataset that each algorithm predicted accurately for each threshold.

![PAlive_threshold_vs_actual_prediction_accuracy](https://user-images.githubusercontent.com/10177608/92096458-7dbee400-ee09-11ea-8ce7-efcdc1a1b768.png)

I thought this is an interesting plot and comparison of the different algorithms.

Herman

**Comment by mmeierer** [comment]
Thanks for sharing. From our experience, this looks plausible. We are currently working on something related, which might at some point be added to CLVTools.

I suppose "naive" uses a threshold of 0.5? 

Your work is related to an evaluation procedure proposed by Wuebben/Wangenheim (2008). See [here](http://www.wuebben.net/members/markus/Home/Publications_files/wuebben%20wangenheim%20JM%202008%20instant%20customer%20base%20analysis_1.pdf).

Are you able to share for which marketing applications you do use the PAlive estimates?
