### ISSUE TITLE
optimx method nlm fails due to named parameters

### ISSUE THREAD

**Issue by oblander** [bachmannpatrick/CLVTools#155]
When setting `method = "nlm"` in the optimx arguments, estimation immediately fails due to the LL function returning an error.

Source of the problem is that the `nlm` function strips names from the parameter vector, while the LL code (at least for the PNBD with dynamic covariates) references parameters by name; this can be fixed e.g. by adding a `parnames` argument to the LL function and reassigning names in the first line of the function.

**Comment by pschil** [comment]
Thanks again for reporting! 
I have been wrongly assuming that the methods have an issue with returned Inf/NaNs
