### ISSUE TITLE
KKT optimality improvement

### ISSUE THREAD

**Issue by sinkRswim** [bachmannpatrick/CLVTools#165]
Hi All, I have three years of retail purchase transaction level data. I keep getting "Warning: The KKT optimality conditions are not both met for the fitted gg spending model", but it does predict the CLV. Does this mean, the CLV predicted is NOT reliable. I do see that P values for S and Beta are high ( not significant). Pls see below.

> est.pnbd <- pnbd(clv.data = clv.train)
Starting estimation...
Estimation finished!
>  summary(est.pnbd)
Pareto NBD Standard  Model 

Call:
pnbd(clv.data = clv.train)

Fitting period:                                
Estimation start  2017-12-31    
Estimation end    2020-09-06    
Estimation length 140.0000 Weeks

 Coefficients:

  | Estimate | Std. Error | z-val | Pr(>\|z\|)
-- | -- | -- | -- | --
r | 0.8835 | 0.1021 | 8.655 | <   0.0000000000000002 ***
alpha | 25.604 | 3.3775 | 7.581 | 0.0000000000000344   ***
s | 0.5035 | 0.6359 | 0.792 | 0.429
beta | 127.5049 | 220.6421 | 0.578 | 0.563

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Optimization info:                 
LL     -6033.2729
AIC    12074.5458
BIC    12090.1998
KKT 1  TRUE      
KKT 2  TRUE      
fevals 38.0000   
Method L-BFGS-B  

Used Options:                 
Correlation FALSE

> results <- predict(est.pnbd, continuous.discount.factor = d ) 
Predicting from 2020-09-07 until (incl.) 2021-01-31 (21.00 Weeks).
Estimating gg model to predict spending...
Starting estimation...
Estimation finished!
_Warning: The KKT optimality conditions are not both met for the fitted gg spending mode_

**Comment by mmeierer** [comment]
The KKT criteria are measures to determine if the optimizer has reached a global optimum. However, those metrics are not perfect, but provide some guidance. 

In your caset the Pareto/NBD model fulfills both criteria (i.e. see your output: 
```
KKT 1 TRUE   
KKT 2 TRUE
```), 
but the Gamma-Gamma model for estimating the average spending per transaction does not meet those criteria. 

Thus, it might make sense to look at the spending model. Please see chapters 2.3 and 2.4 in the CLVTools Walkthrough: https://cran.r-project.org/web/packages/CLVTools/vignettes/CLVTools.pdf

**Comment by sinkRswim** [comment]
@mmeierer  Thank you.
