### ISSUE TITLE
Modeling Conversion

### ISSUE THREAD

**Issue by GabrielSartori** [bachmannpatrick/CLVTools#169]
Hello, i am using clvtools to build a model at my company. I have a problem by index, after create a model with multiple factors in my covariate:

Error in last.row.optimx.coef[1, names.prefixed.covs, drop = TRUE] : 
  índice fora de limites

# my cltvtools data 
![data](https://user-images.githubusercontent.com/34094668/116736710-a31ae680-a9c6-11eb-803e-b40a03688946.png)

```
cltv_cwb_static3 <-SetStaticCovariates(clv.data = clvt_cwb_cov2
    ,data.cov.life = df_cov_idade
    ,data.cov.trans = df_cov_idade
    , names.cov.life = c("cut_idade")
    , names.cov.trans  = c("cut_idade")
    , name.id = "cpf")

est_pnbd_static3 <- pnbd(
    cltv_cwb_static3
    , verbose = TRUE
    # , start.params.model = 
    # c(
    #     # r = coef_est_pnbd[1]
    #     # , alpha = coef_est_pnbd[2]
    #     # , s = coef_est_pnbd[3] 
    #     # , beta = coef_est_pnbd[4]
    #     )
        # , optimx.args = list(control = list(trace = 10), method = "Nelder-Mead")
    )
```

**Comment by bachmannpatrick** [comment]
Thanks for using CLVTools!

On first glance I can't see any issues with your code. Do you get the error when calling `pnbd()?` I guess you are using the latest version of CLVTools (v 0.8).

Can you provide more details on your covariate data (i.e. `summary(df_cov_idade)`)?

**Comment by pschil** [comment]
This looks a lot like a problem we had before when parameters could not be read from the optimx result if the covariate names contained special characters such as "[", ")", "_", etc. 
I though this was fixed in the package a long time ago by using `make.names()` on the covariate names what replaced the special characters with dots. The covariate names in your printed summary should therefore not be "cut_idade(25,50]" but rather like "cut_idade.25.50."

What package version are you using and where did you install it from?

**Comment by bachmannpatrick** [comment]
> This looks a lot like a problem we had before when parameters could not be read from the optimx result if the covariate names contained special characters, such as in your case ("[", ")", "_", etc).
> I though this was fixed in the package a long time ago by using `make.names()` on the covariate names what replaces special characters with dots. The covariate names in your printed summary should therefore not be "cut_idade(25,50]" but rather like "cut_idade.25.50."
> 
> What package version are you using and where did you install it from?

I tested the names used above and could not replicate the issue with version 0.8.

**Comment by GabrielSartori** [comment]
Thanks, the covariates names its wrong, i changed to 20_40
