### ISSUE TITLE
Numerical instabilities in DERT (standard Pareto/NBD)

### ISSUE THREAD

**Issue by bachmannpatrick** [bachmannpatrick/CLVTools#171]
DERT shows numerical instabilities for some (extreme) values (standard Pareto/NBD model). It seems that the instability is caused in the part where the hypergeom functions are used (variables `vPart1` and `vPart2`). The input values there are too close to the allowed range and the output then is too small/high to be properly calculated (in the most extreme cases this will lead to a division by 0).

Solution: check if it is possible to rearrange the formula (e.g. using log-transformations).

**Comment by pschil** [comment]
I have actually discussed this issue with Jeff some weeks ago. It looks like the best solution would be to simply use the `kummerU` function from the `gsl` package instead of separating the calculation into 2 parts.

**Comment by pschil** [comment]
Currently, the confluent hypergeometric function of the second kind required in DERT is implemented as a relation of two terms (`vPart1` and `vPart2`). These may diverge and cause numerical instabilities which may lead to the following issues:

- nonsensical results: very high discount rates lead to large DERT values when they should in fact get lower
- NaNs if parameter beta is large and the discount rate has reasonable values (0.1). This is a common issue.

Replacing the separate terms with the implementation of the gsl library fixes these issues.
