### ISSUE TITLE
Install GSL

### ISSUE THREAD

**Issue by page1** [bachmannpatrick/CLVTools#173]
I got this error:
```
configure: error: gsl-config not found, is GSL installed?
ERROR: configuration failed for package ‘RcppGSL’
```

I needed to install `sudo apt install libgsl-dev` to get this working on ubuntu
[https://askubuntu.com/questions/913493/gsl-config-not-found](https://askubuntu.com/questions/913493/gsl-config-not-found)

Leaving this issue to help whoever runs into it.

**Comment by mmeierer** [comment]
Thanks for comment. You find detailed instructions for each OS in our readme: [https://github.com/bachmannpatrick/CLVTools#installation](https://github.com/bachmannpatrick/CLVTools#installation)

I also added this to our FAQ draft. 

Feel free to get in touch if anything else pops up.
