### ISSUE TITLE
Questions for add time-varying factors to capture seasonal pattern

### ISSUE THREAD

**Issue by chenx2018** [bachmannpatrick/CLVTools#175]
Hello everyone, 

I have some questions for adding time-varying covariates in PNBD model. Based on the weekly tracking plot and some domain experience, I think there may exist **strong monthly seasonality** in my data. Then I plan to add time-varying covariates to capture such pattern. There are several approaches:

1. Adding one integer-valued covariates ranging from [1, 12].
2. Adding 12 dummy variables. 
3. Estimating the contribution of each month, eg. calculate the mean total-sale-amount of each month and scale the mean values into [0, 1], then use the scaled value ranging from [0, 1] as the time-varying covariate.

I tried the first approach but the improvement was not much.  If possible, could you please provide some suggestions?

Also, if I specify `time.unit = "year"` in the `clvdata()` function, the standard PNBD model fitting is faster. Is it possible to add monthly seasonality as time-varying covariates while using `time.unit = "year"`? For the fitting process, is it possible to change the stopping criteria to shorten the time?

Thanks a lot!

**Comment by mmeierer** [comment]
I mostly use option 2. Be aware that often it is strongly advisable to train the data in such a case on transaction histories of =>2 years. Otherwise you might overfit on the patterns in the first year (in many but not all cases).

Be aware that there is a fundamental difference in what you are modeling when using (1) compared to (2), i.e. (1) assumes a linear trend (either positive or negative) from January to February.    

In any case, modeling seasonality might profit from substantial knowledge on the seasonal campaigns of the business. 

While estimation time certainly increases, I usually use to work with weekly data. Using yearly data to model monthly seasonality won't work. 

You can change the arguments for any optimization routine through `optimx.args`, see here: [https://www.rdocumentation.org/packages/CLVTools/versions/0.8.0/topics/pnbd](https://www.rdocumentation.org/packages/CLVTools/versions/0.8.0/topics/pnbd)

**Comment by pschil** [comment]
Besides the important points by Markus also my 2 cents:

> Adding one integer-valued covariates ranging from [1, 12].

This assumes a linear relationship between the month, ie Dec>Nov>Oct. I somewhat doubt that this is what you want, but there might be use cases where this could be desirable.

> Adding 12 dummy variables

You should not use one-hot encoding but conventional dummy encoding: 11 variables and 1 all zero baseline. `SetDynamicCovariates` will convert data of type factor and characer to dummies. You can simply pass for example the month names as covariates ("Jan", "Feb", etc).

> Estimating the contribution of each month, eg. calculate the mean total-sale-amount

For the prediction you would also need to have these sales numbers for the prediction period (the future). Im not sure to what degree this makes sense to use the values of the estimation period also in the prediction period. The relationship/correlation between customer spending and transacting in general is intricate, see for example [Glady et al](https://doi.org/10.1016/j.ijresmar.2014.09.005). 

> if I specify time.unit = "year" in the clvdata() function, the standard PNBD model fitting is faster.

You should not specify the time unit based on speed but on how you define a period conceptually...

> For the fitting process, is it possible to change the stopping criteria to shorten the time?

Yes, see `optimx.args` as pointed out by Markus. See `?optimx` for what you can pass and `?pnbd` for examples how to use it. Especially the tolerance for the convergence criteria (`abstol` and `reltol`) and the maximum number of iterations for NelderMead (`maxit`) are relevant. Use `optimx.args=list(control=list(trace=6))` to track progress.

**Comment by chenx2018** [comment]
Hi guys, thanks for your suggestion!

I followed this approach, 

> `SetDynamicCovariates` will convert data of type factor and characer to dummies. You can simply pass for example the month names as covariates ("Jan", "Feb", etc).

The in-sample fitting looks better than the standard PNBD :)

Extended PNBD fitting:

<img width="770" alt="截屏2021-07-05 下午6 29 16" src="https://user-images.githubusercontent.com/37342983/124457923-efb3e100-ddbe-11eb-99e6-278519592ab4.png">

standard PNBD fitting:

<img width="770" alt="截屏2021-07-05 下午6 29 48" src="https://user-images.githubusercontent.com/37342983/124457954-fe9a9380-ddbe-11eb-9a41-4c0a3860945e.png">

I found the monthly seasonality is significant for the **Purchase Process** but not for the **Attrition Process**. Is it possible to only fit the **Purchase Process** with time-varying covariates by setting the args in `SetDynamicCovariates()`? Since the computation time is pretty long, it would be great to find a way to save some time and do more experiment 🙂

Thanks again for your help! @mmeierer @pschil

**Comment by mmeierer** [comment]
Looks good and matches our experience.

You can try to use a different set of covariates for each of the processes. Please have a look at the arguments `names.cov.life` and `names.cov.trans` for the `pnbd()` command. See here: [https://www.rdocumentation.org/packages/CLVTools/versions/0.8.0/topics/pnbd](https://www.rdocumentation.org/packages/CLVTools/versions/0.8.0/topics/pnbd)
