### ISSUE TITLE
0.9.0 version cannot be installed on arm64 Mac M1

### ISSUE THREAD

**Issue by chenx2018** [bachmannpatrick/CLVTools#199]
Hi there,

The newest version of CLVTools cannot be installed on arm64 Mac. I have installed the `gsl` package, but it seems like R cannot find the right directory due to arm64 different home-brew directory. The error message is the following:

```
install.packages("CLVTools")
Installing package into ‘/Users/userName/Library/R/arm64/4.1/library’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
         binary source needs_compilation
CLVTools  0.8.1  0.9.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) y
installing the source package ‘CLVTools’

trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/CLVTools_0.9.0.tar.gz'
Content type 'application/octet-stream' length 770884 bytes (752 KB)
==================================================
downloaded 752 KB

* installing *source* package ‘CLVTools’ ...
** package ‘CLVTools’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppGSL/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:5:
In file included from /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppGSL/include/RcppGSL.h:25:
/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppGSL/include/RcppGSLForward.h:25:10: fatal error: 'gsl/gsl_vector.h' file not found
#include <gsl/gsl_vector.h> 
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘CLVTools’
* removing ‘/Users/chenxing/Library/R/arm64/4.1/library/CLVTools’
Warning in install.packages :
  installation of package ‘CLVTools’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/tc/k2t27jnx50zc0qmc_v0q8mxc0000gn/T/RtmpwWJuHq/downloaded_packages’
```

I tried this approach, [Transitioning from x86 to arm64 on macOS - experiences of an R user](https://pat-s.me/transitioning-from-x86-to-arm64-on-macos-experiences-of-an-r-user/), but did not work out. 

Any suggestions? 
Thanks a lot!

**Comment by chenx2018** [comment]
I have solved this issue by adding the following to Makevars file

```
CFLAGS=-I/opt/homebrew/include
CPPFLAGS = -I/opt/homebrew/include
CXXFLAGS = -I/opt/homebrew/include
```

**Comment by bachmannpatrick** [comment]
Thanks a lot for updating CLVTools and posting your solution! This issue only occurs if Homebrew is used to install `gsl` on M1 Macs. Some background on the issue:

Homebrew uses `/opt/homebrew` for Apple Silicon, but `usr/local` on Intel-Macs. You can change  the compiler flags to include the new directory using chenx2018's solution:

> ```
> CFLAGS=-I/opt/homebrew/include
> CPPFLAGS = -I/opt/homebrew/include
> CXXFLAGS = -I/opt/homebrew/include
> ```

Alternatively, you can install `gsl` manually (without using Homebrew). It is straight forward:

- Download gsl-latest.tar.gz from [https://ftp.gnu.org/gnu/gsl/](https://ftp.gnu.org/gnu/gsl/) and unzip it.
- Navigate to the unziped folder, e.g. `cd ~/Downloads/gsl-2.7.1`
- run the following commands line by line:

```
sudo make clean
sudo chown -R $USER .
./configure && make
make install
```
