### ISSUE TITLE
Should i be using CET or DERT in my case?

### ISSUE THREAD

**Issue by matheuspetlove** [bachmannpatrick/CLVTools#204]
I'm trying to predict the life time value for the next 3 years using all my  e-commerce data (i.e no holdout). 

Based in the choosen cohort, i have costumers who made their first transaction during 2020-01. From those costumers, i have data until the present day, and the idea is to predict the value for each costumer in the next 3 year.

I undertood that the CET is the " number of transactions to expect from a customer during the prediction period" i.e  the number of transactions in 3 years, and DERT is the number of expected transactions after those 3 years until the "death" of the costumer.

so, shouldn't i be using `CET*Predicted Mean Spending `to estimate the CLV for the next 3 years?

I also noted that for my data,` CET  ~ 14*DERT`.

**Comment by matheuspetlove** [comment]
Here are some of my results:
![Rplot01](https://user-images.githubusercontent.com/95380136/150166941-b94d2db9-12e3-4726-a86e-74b14ab26737.png)

**Comment by matheuspetlove** [comment]
![image](https://user-images.githubusercontent.com/95380136/150167813-c4120119-fe4d-4e5c-8c3c-d1b7ed061aef.png)

**Comment by bachmannpatrick** [comment]
Thanks for using CLVTools!

Let me briefly restate the definitions of CET and DERT for the standard Pareto/NBD model.

**CET: conditional expected transactions**
This is the expected number of transactions of a customer (with given transaction history) **up to a specified time-horizon** (e.g., 3 years). The reported result in not discounted.

**DERT: discounted expected residual transactions**
This is the present value of the expected future transactions for a customer (with given transaction history) **over the entire lifetime** (i.e., up to "infinity"). This value considers a discount factor (by default a 10% continuous rate in CLVTools).

For any setting, the DERT and CET differ by a constant. The ranking of the customers will be identical for both values. The constant is dependent on the setting.

_When should you use what?_ (in the case of the standard Pareto/NBD model)

- If you want to estimate customer lifetime value (CLV, by definition covers the entire lifetime of a customer) you should use DERT and multiply this with predicted customer spending. 
- For estimating customer values up to a specific time period (in your case 3 years) you should use CET and multiply it with predicted customer spending.

CLVTools will provide you predicted customer spending when using the `predict()` command if you have provided customer spending information in the `clvdata()` command. The reported CLV value is DERT*(predicted spending).

I hope this helps!
Patrick
