### ISSUE TITLE
Why average monetary value instead of total monetary value?

### ISSUE THREAD

**Issue by SSMK-wq** [bachmannpatrick/CLVTools#207]
I read about Recency, Frequency and Monetary technique and I see that a customer worth is determined by his total revenue that company achieved from a specific customer.

But I see that for RFM analysis the package, uses Average revenue. Is there any reason why you consider Average revenue only?
If a new customer comes with 2 transactions places huge order for 100K and 200K, then he contributed 300K to the company and could be classified as "New but promising" or "New but Heavy spender" etc.

But doesn't taking average normalize everyone on the equal scale? So, then monetary value doesn't become useful metric to segment customers. Instead we have to use only Recency and Frequency (because they have raw values).

Is there any reason why you think average revenue is better than Total revenue?

**Comment by pschil** [comment]
Im not sure if I can follow entirely. This package does *not* do RFM analysis. I recommend reading the vignette accompanying the package which can also be found here: [Link](https://www.clvtools.com/articles/CLVTools.html)

The transaction models (Pareto/NBD, BG/NBD, etc, all models except the Gamma/Gamma) predict how many more (repeat) transactions each customer will make in the prediction period: **CET**. 
The expression **DERT** which is available for some models, is the number of transactions until Infinity, multiplied with a discount factor [(time value of money)](https://en.wikipedia.org/wiki/Time_value_of_money). See here for more details: [Link](https://github.com/bachmannpatrick/CLVTools/issues/132#issuecomment-665728655).

The Gamma/Gamma spending model predicts how much a customer will on average transact for each of these predicted transactions. Output is: average monetary value per transaction

`CET * (average monetary value per transaction)` = The expected monetary value in the prediction period of each customer

`DERT* (average monetary value per transaction) `= Customer *Lifetime* Value (CLV), how much this customer is worth over his entire lifetime (until Infinity)

You can then do segmenting based on either of these values, both give you an impression of "how much more value" is left in your customers. The resulting values actually take into account all components of RFM. Internally, the models do only require RFM to work, part of what makes them so elegant.
