### ISSUE TITLE
Question for `gg`() function

### ISSUE THREAD

**Issue by chenx2018** [bachmannpatrick/CLVTools#208]
Hi guys, 

1. For the Gamma-Gamma Spending model `gg`(), the default setting is `remove.first.transaction = TRUE`. May I know the reason behind this? I did not get the mathematical reason by checking this paper
 - > Fader PS, Hardie BG (2013). “The Gamma-Gamma Model of Monetary Value.” 

 - The key result in the paper shows

 - ![](https://raw.githubusercontent.com/chenx2018/blogdown-image/main/img/202207111133887.png)

- If the % of single-purchase-customer in a cohort is more than 70%, and we set `remove.first.transaction = TRUE`, which means we only use < 30% of data to estimate the p, q, gamma. Why?

---

2. Another question is about dealing with the **spending amount ($) outlier**. Consider a customer with `x = 1 or 2` in his cbs, and one of his transactions has a huge ($) outlier, which will lead to super large value of his `predict.spending`. Is there any suggestions to solve this issue? I already tried to build more cohort groups (eg. by product categories )

**Comment by pschil** [comment]
Another consequence which you can see from the posted formula is how much the prediction leans towards the observed average vs population mean. x will be +1 larger when not removing the first transaction.  

This is especially noteworthy for zero-repeaters (one-time buyers).
- Removing the first transactions (x=0): the prediction equals the population mean. All zero-repeaters have the exact same prediction.
- Not removing the first transaction (x=1): The prediction will lean towards the value that was observed for them. This can be quite a substantial difference in predictions. Also, zero-repeaters all have different predictions influenced by the value of their only observed transaction.

This is something you might want to consider as well.
