### ISSUE TITLE
Calculating the log-likelihood derivative for usage with the mob function in partykit

### ISSUE THREAD

**Issue by IyarLin** [bachmannpatrick/CLVTools#209]
Hi,

The [mob](https://cran.r-project.org/web/packages/partykit/vignettes/mob.pdf) function from partykit allows one to use decision trees in conjunction with parametric models in a way that the models are fitted to subsets of the population such that parameter instability across those subsets is maximized. I think that the models fitted in CLVTools are a great candidate for that use case.

To implement mob with new models it is required to provide a few pieces of information:
1. The model coefficients
2. Value of the minimized objective function
3.  Empirical estimating functions

The first 2 are readily available in the fitted model object using the `coef` and `logLik` methods. 

The last one I was not able to find skimming through the source code. The empirical estimating function is basically an nXp matrix of log-likelihood derivatives for each individual and model parameter. I thought it was a good idea to ask if that information was stored somewhere in the model object before I try to derive it myself.

**Comment by mmeierer** [comment]
The approach sounds interesting. 

But would you mind sharing what you are aiming for? The Gamma distribution is already quite effective in controlling for individual heterogeneity and key to the reliability of the PNBD's predictions . Form our experience, only in very extreme scenarios such as gaming additional flexibility might be helpful.

**Comment by IyarLin** [comment]
Sure. 

First, the aim is not to control for individual heterogeneity but rather to find how that heterogeneity is a function of individual covariates. E.g. "Female customers from the US have a predicted CLV of $1000, while that of Male customers from India is only $10". 

The CLVTools package does have a way to include covariates in the model but it assumes linearity and no interactions. I'd like to extend that approach to a non-parametric one using decision trees. The idea is to use the tree to find subsets of the customer base where the PNBD estimates are as different as possible.

**Comment by pschil** [comment]
Certainly a very interesting approach for explanatory analysis. 

> Empirical estimating functions

We do not have this available and there are no methods that implement the derivatives of the log-likelihood. But you can of course approximate it by numerical differentiation. For this you will need to call the function pnbd_nocov_ll() and use the CBS values (see slot cbs, x=frequency-1, tx=recency (time of last transaction), Tcal=observation length) as inputs:

```
data('cdnow')
dt.cbs <- CLVTools:::pnbd_cbs(clvdata(cdnow, 'ymd', 'w', 39))
ll <- CLVTools:::pnbd_nocov_LL_ind(vLogparams = c(0.123, 0.234, 0.345, 0.456), vX=dt.cbs$x, vT_x=dt.cbs$t.x, vT_cal=dt.cbs$T.cal)

# Gradient for all
numDeriv::grad(func = CLVTools:::pnbd_nocov_LL_sum, x = c(0.123, 0.234, 0.345, 0.456),
               vX=dt.cbs$x, vT_x=dt.cbs$t.x, vT_cal=dt.cbs$T.cal)
```


You do only have to obtain gradients per unique CBS values as the LL only depends on that. Mind that this is only the gradient for the Pareto/NBD model of repeat transactions and not the gradient of CLV. From your company background I assume that CET should be enough for your use case.

```

# Gradient per cbs / customer
get_num_deriv <- function(SD){
  stopifnot(nrow(SD) == 1)
  grads <-numDeriv::grad(func = CLVTools:::pnbd_nocov_LL_sum, x = c(0.123, 0.234, 0.345, 0.456),
                         vX=SD$x, vT_x=SD$t.x, vT_cal=SD$T.cal)
  return(list(grads[1], grads[2], grads[3], grads[4]))
}

cols.by<- c('x', 't.x', 'T.cal')
dt.cbs.unique <- unique(dt.cbs[, .SD, .SDcols=cols.by])
# alternative if only count is relevant
# dt.cbs.unique <- dt.cbs[, .N, by=cols.by]
dt.cbs.unique[, c('log.r', 'log.alpha', 'log.s', 'log.beta') := get_num_deriv(.SD), by=cols.by, .SDcols=cols.by]
dt.cbs[dt.cbs.unique, on=cols.by]

```

Mind that the params are at log-scale and then exp()-ed internally in the LL so the gradients actually are for the log()ed params.


How different do you expect results to be from fitting a single model and doing partitioning directly on predicted CLV or CET?


CLV / CET as predicted by the models in this package is a (highly non-linear) function of the CBS values and average spending. I suspect that partitioning on the CBS values directly could still lead to somewhat similar results but very interested to hear about your findings!

**Comment by IyarLin** [comment]
We do have many datasets we could use to see if using MOB or just splitting on predicted CET/CLV/CBS yield very different results. 
Appreciate your advice. I'll keep you posted on further developments.
