### ISSUE TITLE
Evaluating model performance - missing?

### ISSUE THREAD

**Issue by SSMK-wq** [bachmannpatrick/CLVTools#210]
Thanks for this wonderful package and awesome tutorial.

My question is on assessing the model performance. Based on the screenshot from walkthrough page, I have two questions and they are

![image](https://user-images.githubusercontent.com/30723825/200467122-a43b70d8-8298-4b36-bbde-62d68b764aef.png)

a) Isn't there no train and test split for building and assessing the models? then is training using full dataset recommended or right thing to do? If yes, can shed some insights on how training using full dataset is useful for models like this (and how they are different from traditional ML models like random forest etc)

b) I also see that model overpredicts the spending of a customer who has ZERO as actual value. And this behavior is same for all other customers with Zero as actual spending. Does model take population mean or something for prediction? So, how do we assess the model performance?

Should we compute traditional "R2", "RMSE" etc?

Is there any inbuilt approach within CLVTools package to assess the model performance

**Comment by bachmannpatrick** [comment]
Hi!

a) There is an estimation period and a holdout period (if specified). The estimation split is defined in `clvdata()` using the `estimation.split` argument. If `estimation.split=NULL` there is no holdout period.

b) A customer having 0 spending during the holdout period, does not mean that this customer has not purchased during the estimation period. There was just no transaction (or only transactions with Price=0) during the holdout period. The population mean is only used if a customer is not observed at all (no repeated transactions during estimation period).

We do not include an approach in CLVTools to assess model performance. I would suggest using the `accuracy()` command of the package `forecast`.

Best,
Patrick

**Comment by mmeierer** [comment]
Most approaches for modeling CLV (no matter, if probabilistic or not) start from the assumption that you split up your data in cohorts (and thereby, look at customers' tenure as the relevant time reference and not calendar time). For more information, see here: [https://github.com/bachmannpatrick/CLVTools/issues/172#issuecomment-862151684 ](https://github.com/bachmannpatrick/CLVTools/issues/172#issuecomment-862151684 ). Meaning, you will estimate a separate model for each cohort. 

For every, cohort dataset you can choose an individual train/test period. Depending on your data, we often recommend to use at least 1 year for training. 

The toy dataset that comes with CLVTools are the purchase records for a single cohort of a apparel retailer ([https://rdrr.io/cran/CLVTools/man/apparelTrans.html](https://rdrr.io/cran/CLVTools/man/apparelTrans.html)). 

As far as I understand, following the standard workflow for modeling CLV should solve the issues that you describe above.
