### ISSUE TITLE
Interpreting Coefficients With Covariates

### ISSUE THREAD

**Issue by tom-from-goss** [bachmannpatrick/CLVTools#212]
Hello CLVTools and thank you for the fantastic package.

I'm fitting models with covariates and was wondering how to interpret estimates of coefficients. Based on the note referenced on Bruce Hardie's website it seems that the correct interpretation for a binary covariate is that for transactions we have exp(-gamma) = alpha/alpha_0, where gamma is the coefficient. Hence a value over one shows an increase in the base model alpha, a value below 1 shows a decrease in the base model alpha.

Is this correct? Any help would be highly valued.

Kind regards,

Tom

**Comment by bachmannpatrick** [comment]
Hi Tom!

To which of Bruce's notes are you exactly referring? 

Thanks,
Patrick

**Comment by pschil** [comment]
The covariates in the note act as a stretching factor on the original parameter.
But mind that there is a slight change in notation between the no covariate and the static covariate models. The parameters `alpha` and `beta` reported by CLVTools for static covariates correspond to `alpha_0` and `beta_0` in the note. 

If you fit with a binary dummy covariate you will get two groups of customers, each with their own, different alpha and beta.

Example:
Reported parameter `alpha=1.23` which is `alpha_0` in the note and `g_1=-0.25`. 

For dummy z=0: 
`alpha=alpha_0*exp(-g_1'z)=alpha_0*1=1.23`.

For dummy z=1
`alpha=alpha_0*exp(-g_1'z)=alpha_0*exp(0.25)=1.23*1.28=1.579`

May I ask how you became aware of CLVTools?

**Comment by tom-from-goss** [comment]
Excellent, that's how i was interpreting the coefficients. Thank you.

I became aware of the package from googling 'Pareto/NBD in R!
