### ISSUE TITLE
Interpreting time-invariant covariate coefficients

### ISSUE THREAD

**Issue by tm185246** [bachmannpatrick/CLVTools#218]
After reading through the CLVTools documentation and reading the referenced papers, I am still slightly confused on how to interpret the coefficients for time-invariant covariates. According to the documentation, _"A 1% change in a contextual factor XP or XL changes the purchase or the attrition rate by 𝛾𝑝𝑢𝑟𝑐ℎXP or 𝛾𝑙𝑖𝑓𝑒XL percent, respectively."._ However, in the provided example, the time-invariant covariates are binary (e.g. gender covariate: 1 for female and 0 for male). How can we have a 1% increase in a binary variable? And if we were dealing with a variable that could be 0,1,2,3,4,5 - how would we interpret this variable's coefficient?

Thanks for any help in advance!

**Comment by bachmannpatrick** [comment]
Please see the following FAQ Issue: #212
