### ISSUE TITLE
In plot() how to get red line?

### ISSUE THREAD

**Issue by eat-toast** [bachmannpatrick/CLVTools#219]
Is there a way to get the data for the red line in the plot() function?

![image](https://github.com/bachmannpatrick/CLVTools/assets/31301664/9002bc7d-f21b-4919-8d53-4195c3bcdaae)

**Comment by pschil** [comment]
you can get the data used to create the plot from the plotting method itself by passing `plot=FALSE`

```
data("apparelTrans")
clv.data.apparel <- clvdata(apparelTrans, date.format = "ymd", time.unit = "w", estimation.split = 40)
p.apparel <- pnbd(clv.data.apparel)
dt.data <- plot(p.apparel, plot=FALSE)
dt.data

```
This works for all plots, check `?plot.clv.fitted.transactions`.
