### ISSUE TITLE
estimation.split = NULL error "Parameter estimation.split needs to be at least 1 time.unit

### ISSUE THREAD

**Issue by AdimDrewnik** [bachmannpatrick/CLVTools#220]
When using estimation.split = NULL I am getting error "Parameter estimation.split needs to be at least 1 time.unit after the start!" for short cohorts. This probably should not be the case if I want to fit model without hold out period. 

>  DATA = clvdata(data_cohort, 
+                  date.format = "ymd",
+                  time.unit   = "years",
+                  name.id     = "ID",
+                  name.date   = "Date",
+                  name.price  = "Price",
+                  estimation.split = NULL )
 Parameter estimation.split needs to be at least 1 time.unit after the start!

**Comment by mmeierer** [comment]
Duplicate. Closed.
