### ISSUE TITLE
How to handle cost data in CLVTools

### ISSUE THREAD

**Issue by AdimDrewnik** [bachmannpatrick/CLVTools#225]
In CLVTools there is a gamma-gamma model to handle customer spending data. Assume that for each individual customer and single spend data there is also a cost associated. What is a typical way to handle cost data? Simply subtract cost from spend and make it an input to gamma-gamma model? What if cost is higher than spend and it gives negative spend which is not allowed in gamma-gamma model?

**Comment by bachmannpatrick** [comment]
Hi,

Yes, the "normal" way to handle cost is to calculate profit and feed that into the Gamma/Gamma model. Most companies we know of, however, focus on revenue rather that profit (simply because individual cost attribution is very challenging).

Unfortunately the current implementation of the Gamma/Gamma model does not allow for negative spending. This is relatively easy to solve model wise, however it is just not implemented yet. We do have that on our feature list (but as priority).

Best,
Patrick

**Comment by AdimDrewnik** [comment]
Thank you. That was very helpful.

**Comment by mmeierer** [comment]
Good points. 

To wrap up the issue:
Profit per transaction, i.e., customer spending minus costs of the business, can become negative for specific transactions. However, the Gamma/Gamma model has originally been proposed to only model inherently positive customer spendings. 

To add to Patrick’s comments:
While methodologically possible, modifying the GG model to account for negative values would not solve another rather theoretical problem. While important, considering costs is outside the focus of the original "story" of this modeling approach and its emphasis on customer decision-making processes:
- A customer makes the decision to spend a certain amount of money per transaction (GG model). At the same time, a customer makes the decision to continue doing business with a firm (“Pareto part” of the PNBD model) and a customer makes the decision of how many transactions to make (“NBD part” of the PNBD model).
- Costs/profits are inherently a business issue. In other words, a firm’s profit margin per transaction is not known to the customer. Thus, it is not a customer-decision making process that we would model in this case.  

The most rigorous approach would likely be to have a separate, additional model for the cost per transaction. This would allow considering specific determinants of the individual costs for each product.

However, if you are looking for a “hands-on approach” modeling profits with the GG model and related extensions may work. But this depends on your specific business setting. However, be aware that you are mixing up two fundamentally different processes (revenue and cost).
