### ISSUE TITLE
Integrate the functionality of RcppEigen

### ISSUE THREAD

**Issue by mmeierer** [bachmannpatrick/CLVTools#25]
Integrate the functionality of the package RcppEigen 
- [ ] Package setup
- [ ] pnbd_LL
- [ ] pnbd_CET
- [ ] pnbd_DERT
- [ ] pnbd_palive
- [ ] clv_vectorized
- [ ] Benchmark vs RcppArmadillo LLs
- [ ] tests on rhub (win, linux)

**Comment by pschil** [comment]
Interesting comparison but will not implement
