### ISSUE TITLE
Can CLVTools be used for subscription business? 

### ISSUE THREAD

**Issue by MengyingLi** [bachmannpatrick/CLVTools#251]
Hi I am trying to figure out how to use CLVTools for SaaS subscription business but all the examples are one-time transactions. Can this tool be used for SaaS? The only thing I found online is from this article https://www.r-bloggers.com/2018/09/ltv-prediction-for-a-recurring-subscription-with-r/

**Comment by mmeierer** [comment]
The models implemented in CLVTools are exclusively desgined to model customer relationships in non-contractual settings. There are contractual settings where it does make sense to apply these models, but these are rather the exception than the rule. 

The main factor of differentiation is that non-contractual models have to estimate when a customer stops doing business with a firm - even though the customer never formally give the business a notice on this. In contractual settings such as SaaS business, a customer has to formally cancel a subscription. This additional information make the modeling task more straightforward for contractual businesses.
