### ISSUE TITLE
Address “Prediction Period 1” issue

### ISSUE THREAD

**Issue by mmeierer** [bachmannpatrick/CLVTools#28]
Address “Prediction Period 1” issue

**Comment by pschil** [comment]
- [ ] Implement different math for k_{T, T+t}==1
- [ ] tests to verify k_{T,T+t}==1 case is correctly distinguished
- [ ] tests for correct creation of prediction table
- [ ] adapt inputchecks to newly verify whole prediction period is >= 0
- [ ] test for running with prediction periods <= 2
